import React from "react";
import Head from "next/head";
import NavBar from "../components/NavBar";
import FooterGrid from "@/components/FooterGrid";
import BlogGrid from "@/components/BlogGrid";

import HubNav from "@/components/hub/HubNav";
import {useState, useEffect} from "react"
import { firebaseApp, firestore } from "./util/firebase";
import {getStorage } from "firebase/storage"
import { collection, getDocs, getFirestore  } from "firebase/firestore";


export default function BlogHome() {
    console.log("Hello")
const [Blogs, setBlogs] = useState([]); 
const db = getFirestore(firebaseApp);
const storage = getStorage(firebaseApp );

    useEffect(()=> {
        ; (async () =>{
            const collectionRef = collection(db, "tutorials")
            const  snapshots = await getDocs(collectionRef)
            const docs = snapshots.docs.map(doc => {
              const data = doc.data()
              data.id = doc.id
              return data
            })
            
            setBlogs(docs)
        })()
      }, [])
      console.log("Blogs:", Blogs)

return (
    <>
      <Head>
        <title>Zheé Gym Hub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

      </Head>

      <main>
        <NavBar showElement></NavBar>
        <HubNav ></HubNav>
        <BlogGrid  blogList={Blogs}></BlogGrid>
        <FooterGrid></FooterGrid>
       
      </main>
    </>
  );
}