import React from "react";
import Head from "next/head";
import NavBar from "../components/NavBar";
import FooterGrid from "@/components/FooterGrid";
import BlogGrid from "@/components/BlogGrid";
import Nav from 'react-bootstrap/Nav';
import Form from 'react-bootstrap/Form';
import Button from 'react-bootstrap/Button';
import {useState, useEffect} from "react"
import { firebaseApp, firestore } from "../util/firebase";
import {getStorage } from "firebase/storage"
import { collection, getDocs, getFirestore  } from "firebase/firestore";


export default function BlogHome() {
const [Blogs, setBlogs] = useState([]); 
const db = getFirestore(firebaseApp);
const storage = getStorage(firebaseApp );
const [searchTerm, setSearchTerm] = useState("");

useEffect(()=> {
  ; (async () =>{
    const collectionRef = collection(db, "blogs")
      const  snapshots = await getDocs(collectionRef);
      const docs = snapshots.docs.map(doc => {
        const data = doc.data()
        data.id = doc.id
        return data
      })
      
      setBlogs(docs)
  })()
}, [db])

      const handleInputChange = (event) => {
        console.log(event.target.value)
        setSearchTerm(event.target.value);
      };

    const handleSearch = async (event) => {
      try{
        const filteredBlogs = Blogs.filter((selectedBlog) =>
        selectedBlog.blogTitle.toLowerCase().includes(searchTerm.toLowerCase())
      );
      setBlogs(filteredBlogs)
      console.log("updatedBlogs;", Blogs)
       } catch (e) {
        console.log(e);
        alert("Blog not found")
      };
        
      };

     

return (
    <>
      <Head>
        <title>Zheé Gym Hub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

      </Head>

      <main>
        <NavBar showElement></NavBar>

        <Nav className="hubnav"  defaultActiveKey="/home">
          <Form className="searchbar">
            <Form.Control className="bar" type="search"placeholder="Search" onChange={handleInputChange} value={searchTerm}/>
            <Button onClick={handleSearch}>Search</Button>
          </Form> 
        </Nav>
        <BlogGrid  blogList={Blogs}></BlogGrid>
        <FooterGrid></FooterGrid>
       
      </main>
    </>
  );
}