import React from "react";
import Head from "next/head";
import NavBar from "../components/NavBar";
import FooterGrid from "@/components/FooterGrid";
import TextCard from "@/components/TextCard";
import VideoGrid from "@/components/hub/VideoGrid";
import HubNav from "@/components/hub/HubNav";



function getVideos() {

  return fetch("/api/videos", {
    method: "GET"
  })
    .then((response) => response.json())
    .then((data) => data)
    .catch((error) => console.error(error));
}

export default function ZheeHub() {
  const [isLoading, setIsLoading] = React.useState(false);
  const [error, setError] = React.useState(false);
  const [videos, setVideos] = React.useState([]);

  React.useEffect(() => {
    setIsLoading(true);
    getVideos()
      .then((response) => {
        setVideos(response);
        setIsLoading(false);
      })
      .catch((error) => {
        console.error(error);
        setError(true);
      });
  }, []);

  if (isLoading) return <div>Loading...</div>;
  if (error) return <div>Error...</div>;

  return (
    <>
      <Head>
        <title>Zheé Gym Hub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

      </Head>

      <main>
        <NavBar></NavBar>
        <TextCard cardclassName= "textcard-hub" titleclassName="textcard-title" textclassName= "textcard-text"  ></TextCard>
        <HubNav ></HubNav>
        <VideoGrid videos={videos} ></VideoGrid>
        <FooterGrid></FooterGrid>
       
      </main>
    </>
  );
}