import React from "react";
import Head from "next/head";
import NavBar from "../components/NavBar";
import FooterGrid from "@/components/FooterGrid";
import TextCard from "@/components/TextCard";
import VideoGrid from "@/components/hub/VideoGrid";
import HubNav from "@/components/hub/HubNav";
import {ref, getDownloadURL, listAll } from "firebase/storage"
import {useState, useEffect} from "react"
import { firebaseApp, firestore } from "./util/firebase";
import {getStorage } from "firebase/storage"
import { collection, getDocs, getFirestore  } from "firebase/firestore";


export default function ZheeHub() {
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(false);
  const [videos, setVideos] = useState([]); 
  const storage = getStorage(firebaseApp );
  const tutotialListRef = ref(storage, "tutorial-videos")
  const db = getFirestore(firebaseApp);
  
if (isLoading) return <div>Loading...</div>;
if (error) return <div>Error...</div>;

//get list of thumbanil from firebase storage
    useEffect(()=> {
      ; (async () =>{
          const collectionRef = collection(db, "tutorials")
          const  snapshots = await getDocs(collectionRef)
          const docs = snapshots.docs.map(doc => {
            const data = doc.data()
            data.id = doc.id
            return data
          })
          
          setVideos(docs)
      })()
    }, [])

    
    console.log("videos", videos)
  return (
    <>
      <Head>
        <title>Zheé Gym Hub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

      </Head>

      <main>
      <div class="scroll-up-btn">
         <i class="fas fa-angle-up"></i>
      </div>
        <NavBar></NavBar>
       { /*<TextCard cardclassName= "textcard-hub" titleclassName="textcard-title" textclassName= "textcard-text"  ></TextCard>*/}
        <HubNav ></HubNav>
        <VideoGrid videosTutorials={videos} ></VideoGrid>  
        <FooterGrid></FooterGrid>
       
      </main>
    </>
  );
}