import React from "react";
import Head from "next/head";
import NavBar from "../components/NavBar";
import FooterGrid from "@/components/FooterGrid";
import TextCard from "@/components/TextCard";
import VideoGrid from "@/components/hub/VideoGrid";
import Nav from 'react-bootstrap/Nav';
import Form from 'react-bootstrap/Form';
import Button from 'react-bootstrap/Button';
import HubNav from "@/components/hub/HubNav";
import {ref, getDownloadURL, listAll } from "firebase/storage"
import {useState, useEffect} from "react"
import { firebaseApp, firestore } from "../util/firebase";
import {getStorage } from "firebase/storage"
import { collection, getDocs, getFirestore  } from "firebase/firestore";


export default function ZheeHub() {
  const [videos, setVideos] = useState([]); 
  const storage = getStorage(firebaseApp );
  const tutotialListRef = ref(storage, "tutorial-videos")

const [searchTerm, setSearchTerm] = useState("");

  const db = getFirestore(firebaseApp);
  

//get list of thumbanil from firebase storage
    useEffect(()=> {
      ; (async () =>{
          const collectionRef = collection(db, "tutorials")
          const  snapshots = await getDocs(collectionRef)
          const docs = snapshots.docs.map(doc => {
            const data = doc.data()
            data.id = doc.id
            return data
          })
          
          setVideos(docs)
      })()
    }, [db])

    const handleInputChange = (event) => {
      console.log(event.target.value)
      setSearchTerm(event.target.value);
    };

  const handleSearch = async (event) => {
    try{
      const filteredTutorials = videos.filter((selectedTutorial) =>
      selectedTutorial.title.toLowerCase().includes(searchTerm.toLowerCase())
    );
    setVideos(filteredTutorials)
    console.log("updatedBlogs;", Blogs)
     } catch (e) {
      console.log(e);
    };
      
    };


  return (
    <>
      <Head>
        <title>Zheé Gym Hub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

      </Head>

      <main>
      <div className="scroll-up-btn">
         <i className="fas fa-angle-up"></i>
      </div>
        <NavBar></NavBar>
       <Nav className="hubnav"  defaultActiveKey="/home">
          <Form className="searchbar">
            <Form.Control className="bar" type="search"placeholder="Search" onChange={handleInputChange} value={searchTerm}/>
            <Button onClick={handleSearch}>Search</Button>
          </Form> 
        </Nav>
        <VideoGrid videosTutorials={videos} ></VideoGrid>  
        <FooterGrid></FooterGrid>
      </main>
    </>
  );
}