import React from "react";
import Head from "next/head";
import ProductGrid from "../components/ProductGrid";
import NavBar from "../components/NavBar";
import Carousel from "../components/Carousel";
import ParagraphGridImageGrid from "../components/ParagraphImageGrid";
import ContactUsForm from "@/components/ContactUsForm";
import FooterGrid from "@/components/FooterGrid";
import NavBarHome from "@/components/NavBarHome";


import {useState, useEffect} from "react"
import { firebaseApp, firestore } from "../util/firebase";
import {getStorage } from "firebase/storage"
import { collection, getDocs, getFirestore  } from "firebase/firestore";



export default function Home() {
  const [isLoading, setIsLoading] = React.useState(false);
  const [error, setError] = React.useState(false);
  const [products, setProducts] = useState(); 
  const db = getFirestore(firebaseApp);
  const storage = getStorage(firebaseApp )

  useEffect(()=> {
    ; (async () =>{
        const collectionRef = collection(db, "product")
        const  snapshots = await getDocs(collectionRef)
        const docs = snapshots.docs.map(doc => {
          const data = doc.data()
          data.id = doc.id
          return data
        })
        
        setProducts(docs)
    })()
  }, [])


  if (isLoading) return <div>Loading...</div>;
  if (error) return <div>Error...</div>;

  return (
    <>
      <Head>
        <title>Zheé Gym Hub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

      </Head>

      <main className="index-main">
       <div class="scroll-up-btn">
         <i class="fas fa-angle-up"></i>
      </div> 
        <NavBarHome showElement ></NavBarHome>
        <Carousel></Carousel>
        <ParagraphGridImageGrid></ParagraphGridImageGrid>
        <ProductGrid products={products} />
        <ContactUsForm></ContactUsForm>
        <FooterGrid></FooterGrid>
       
      </main>
    </>
  );
}