import React from "react";
import Head from "next/head";
import ProductGrid from "../components/ProductGrid";
import NavBar from "../components/NavBar";
import Carousel from "../components/Carousel";
import ParagraphGridImageGrid from "../components/ParagraphImageGrid";
import ContactForm from "@/components/SignInForm";
import ContactUsForm from "@/components/ContactUsForm";
import FooterGrid from "@/components/FooterGrid";



function getProducts() {

  return fetch("/api/products", {
    method: "GET"
  })
    .then((response) => response.json())
    .then((data) => data)
    .catch((error) => console.error(error));
}

export default function Home() {
  const [isLoading, setIsLoading] = React.useState(false);
  const [error, setError] = React.useState(false);
  const [products, setProducts] = React.useState([]);

  React.useEffect(() => {
    setIsLoading(true);
    getProducts()
      .then((response) => {
        setProducts(response);
        setIsLoading(false);
      })
      .catch((error) => {
        console.error(error);
        setError(true);
      });
  }, []);

  if (isLoading) return <div>Loading...</div>;
  if (error) return <div>Error...</div>;

  return (
    <>
      <Head>
        <title>Zheé Gym Hub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

      </Head>

      <main>
        <NavBar></NavBar>
        <Carousel></Carousel>
        <ParagraphGridImageGrid></ParagraphGridImageGrid>
        <ProductGrid products={products} />
        <ContactUsForm></ContactUsForm>
        <FooterGrid></FooterGrid>
       
      </main>
    </>
  );
}