import React from "react";
import Head from "next/head";
import NavBar from "../components/NavBar";
import FooterGrid from "@/components/FooterGrid";
import VerticalGrid from "@/components/hub/VerticalGrid";
import VideoPlayer from "@/components/VideoPlayer";


function PlayVideos() {
  
  return (
    <>
      <Head>
        <title>Zheé Gym Hub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
      </Head>

      <main>
        <NavBar></NavBar>
        <VideoPlayer ></VideoPlayer>
        <FooterGrid></FooterGrid>
       
      </main>
    </>
  );
}

export default PlayVideos;