import React from "react";
import Head from "next/head";
import NavBar from "../components/NavBar";
import FooterGrid from "@/components/FooterGrid";
import VerticalGrid from "@/components/hub/VerticalGrid";
import {ref, onValue } from "firebase/storage"
import db from "src/pages/handlingfirebas";
import {useState, useEffect, listAll} from "react"

 


function getVideos() {
  const [tutotialList, setTutorialList] = useState([]);
  const tutotialListRef = ref(storage, "tutorials")
  /*
  return fetch("/api/videos", {
    method: "GET"
  })
    .then((response) => response.json())
    .then((data) => data)
    .catch((error) => console.error(error));
  }

export default function ZheeHub() {
  const [isLoading, setIsLoading] = React.useState(false);
  const [error, setError] = React.useState(false);
  const [videos, setVideos] = React.useState([]);

  React.useEffect(() => {
    setIsLoading(true);
    getVideos()
      .then((response) => {
        setVideos(response);
        setIsLoading(false);
      })
      .catch((error) => {
        console.error(error);
        setError(true);
      });
  }, []);
*/
  if (isLoading) return <div>Loading...</div>;
  if (error) return <div>Error...</div>;


  useEffect(()=> {
listAll(tutotialListRef).then((response) => {
  console.log(response)
})
  }, [])
  
  return (
    <>
      <Head>
        <title>Zheé Gym Hub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

      </Head>

      <main>
        <NavBar></NavBar>
        <VerticalGrid videos={videos}></VerticalGrid>
        <FooterGrid></FooterGrid>
       
      </main>
    </>
  );
}